<a href="https://colab.research.google.com/github/bartaLevente/udemy_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

#Tensors

In [3]:
print(tf.__version__)

2.18.0


In [4]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [5]:
vector = tf.constant([2,4])
print(vector)
print(vector.ndim)

tf.Tensor([2 4], shape=(2,), dtype=int32)
1


In [6]:
matrix = tf.constant([[1.,2],
                      [4,5]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[1. 2.]
 [4. 5.]], shape=(2, 2), dtype=float32)
2


In [7]:
tensor = tf.constant([
    [[1,2],[1,2]],
    [[1,2],[1,2]],
])

print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]], shape=(2, 2, 2), dtype=int32)
3


In [8]:
tensor2 = tf.Variable([12,12,12])

tensor2[0].assign(7)
tensor2

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 7, 12, 12], dtype=int32)>

In [9]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [10]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.uniform(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [11]:
tf.random.set_seed(42)

shuffled = tf.random.shuffle(random2,seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [12]:
tf.ones(5)
tf.zeros(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [13]:
import numpy as np

np_A = np.arange(1,25, dtype=np.int32)

A = tf.constant(np_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

#Tensor attributes

In [21]:
print(A.shape)
print(A.ndim)
print(tf.size(A).numpy())
print(A[:, 1].numpy())
print(A.dtype)

(2, 3, 4)
3
24
[[ 5  6  7  8]
 [17 18 19 20]]
<dtype: 'int32'>


#Tensor indexing

In [24]:
tensor = tf.random.Generator.from_seed(42)
tensor = tensor.normal(shape=(2,3,4,5,6))
tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
           -0.23193763, -1.8107855 ],
          [ 0.09988727, -0.50998646, -0.7535805 , -0.57166284,
            0.1480774 , -0.23362993],
          [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,
            1.6874489 , -0.4462975 ],
          [-2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ,
           -0.6161736 , -1.9441465 ],
          [-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ,
           -1.5184573 , -0.4585211 ]],

         [[ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 ,
           -1.2659091 , -0.47450137],
          [ 2.006022  ,  0.28288034, -0.30288252, -1.443651  ,
            1.0034493 ,  0.20857747],
          [ 0.35700995,  1.0648885 ,  1.2432485 , -2.2173238 ,
            0.18706243,  0.6617961 ],
          [ 0.01380118, -0.24827152,  1.2111493 , -0.7199124 ,
           -0.04082382,  2.6791053 ],
          [ 1.0914806 ,  0.33149

In [29]:
tensor[:1,:1,:1,:1, :].numpy()

array([[[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
           -0.23193763, -1.8107855 ]]]]], dtype=float32)

In [33]:
rank2tensor = tf.ones(shape=(2,2))
rank2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [34]:
rank3tensor = rank2tensor[...,tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [38]:
rank4tensor = tf.expand_dims(rank3tensor, axis=-1)
rank4tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]]]], dtype=float32)>

#Manipulating tensors

In [39]:
rank2tensor + 4

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.]], dtype=float32)>

In [40]:
rank2tensor * 0.1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.1, 0.1],
       [0.1, 0.1]], dtype=float32)>

In [41]:
tf.multiply(rank2tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float32)>

In [42]:
tf.matmul(rank2tensor,rank2tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [44]:
X = tf.random.Generator.from_seed(42)
X = X.normal(shape=(2,3))
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [45]:
tf.matmul(rank2tensor, X)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-2.0139647 , -0.30048466, -1.7348353 ],
       [-2.0139647 , -0.30048466, -1.7348353 ]], dtype=float32)>

In [46]:
tf.matmul(tf.transpose(X), X)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.1534293 , 0.34349608, 2.219391  ],
       [0.34349608, 0.05849376, 0.41478315],
       [2.219391  , 0.41478315, 3.2847128 ]], dtype=float32)>

In [47]:
tf.matmul(X, tf.transpose(X))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.58288085, 0.8296813 ],
       [0.8296813 , 4.913755  ]], dtype=float32)>

In [48]:
B = tf.constant([1.74,7.426])
B.dtype

tf.float32

In [52]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [66]:
print(tf.abs(X))
print(tf.reduce_max(X))
print(tf.reduce_min(X))
print(tf.reduce_mean(X))
print(tf.reduce_sum(X))
print(tf.argmin(X))
print(tf.argmax(X))

tf.Tensor(
[[0.7565803  0.06854702 0.07595026]
 [1.2573844  0.23193763 1.8107855 ]], shape=(2, 3), dtype=float32)
tf.Tensor(0.07595026, shape=(), dtype=float32)
tf.Tensor(-1.8107855, shape=(), dtype=float32)
tf.Tensor(-0.6748808, shape=(), dtype=float32)
tf.Tensor(-4.049285, shape=(), dtype=float32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor([0 0 0], shape=(3,), dtype=int64)


In [67]:
rank4tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]]]], dtype=float32)>

In [69]:
tf.squeeze(rank4tensor), tf.squeeze(rank4tensor).shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 TensorShape([2, 2]))

In [74]:
some_list = [0,1,2,3]
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [75]:
C = tf.range(1,10)
C

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
tf.square(C)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [77]:
D = tf.cast(C,dtype=tf.float32)
tf.sqrt(D)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [79]:
tf.math.log(D)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensors and Numpy

In [80]:
import numpy as np

In [82]:
E = tf.constant(np.array([3.,4.,5.,6.]))
E

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([3., 4., 5., 6.])>

In [86]:
np_E = np.array(E)
# or np_E = E.numpy()
np_E

array([3., 4., 5., 6.])

In [89]:
tf_E = tf.constant([3.,4.,5.,6.])

In [90]:
np_E.dtype, tf_E.dtype

(dtype('float64'), tf.float32)

# GPU

In [91]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Sun May  4 15:53:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----